version: '3'

services:
  msrp:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./app/:/usr/src/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - loglevel=warning
