apiVersion: v1
kind: Pod
metadata:
  name: raushanode
  labels:
    app: raushanode
spec:
  containers:
  - name: raushanode
    image: raushanraja/raushanode:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
