apiVersion: v1
kind: Pod
metadata:
   name: tomcat-mongo
spec:
   containers:
   - name: tomcat
     image: bitnami/tomcat:latest
     ports:
     - containerPort: 7500
     imagePullPolicy: Always
   - name: database
     image: bitnami/mongodb:latest
     ports:
     - containerPort: 7501
     imagePullPolicy: Always