- hosts : all
  become: yes
  tasks:
    - name: Install GPG Related Packages
      apt:
        update_cache: yes
        name:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
          - tmux
        state: present
    - name: Install System and other related packages
      apt:
        name:
          - dpkg-dev
          - git
          - curl
          - wget
          - libssl-dev
          - python3-dev
          - python3-pip
        state: present
