Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  # config.vm.network "private_network", ip: "192.168.56.27"
  config.vm.network "public_network", ip: "192.168.68.71"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2000"
    vb.cpus = 2
  end
end
